platform :ios, '11.0'
use_frameworks!

target 'Runner' do
  # プラグインの設定を追加する
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
